# Generated by Django 3.0 on 2021-06-16 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=datetime.datetime(2021, 6, 16, 3, 38, 19, 367650, tzinfo=utc), upload_to='profile_image/'),
            preserve_default=False,
        ),
    ]
