# Generated by Django 3.0 on 2021-07-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_image/default_jtqr8g.jpg', null=True, upload_to='profile_image/'),
        ),
    ]
