# Generated by Django 3.0 on 2021-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210702_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_image/default_jtqr8g.jpg', upload_to='profile_image/'),
        ),
    ]
