# Generated by Django 3.0 on 2021-01-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210124_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('standard', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=1, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
